### ISSUE TITLE
database.entrez.efetch_single_file can not append to existing file

### ISSUE THREAD

**Issue by dombrowsky** [biotite-dev/biotite#106]
The function database.entrez.efetch_single_file() should have the possibility to append to an existing MultiGenBankFile to enable the user to store information from different fetch jobs in one file, as it is not possible to obtain information for more than about 300 ids at the same time. Also, the possibility to automatically delete an already obtained file should be added.

**Comment by padix-key** [comment]
Biotite is able to download GenBank files as *file-like* object, which is actually a thin wrapper around the string of the GenBank file text. You append this string to an existing file using Python's usual file input/output functionality.
```python
file_like_object = entrez.fetch_single_file(
    ids, file_name=None, db_name="protein", ret_type="gb"
)
with open("existing_file.gb", "a") as file:
    file.write("\n")
    file.write(file_like_object.read())
```

Deleting files is out of `Biotite's` scope. But you can simply call `os.remove("path/to/the/file")` or download the file directly into a temporary directory.
