### ISSUE TITLE
sequence.io.genbank.GenBankFile should also parse the Organism line

### ISSUE THREAD

**Issue by dombrowsky** [biotite-dev/biotite#107]
The GenBankFile object should also contain the ORGANISM field as a subfield of SOURCE, as otherwise the taxonomy of an entry can not be retrieved.

**Comment by padix-key** [comment]
The new GenBank file interface of Biotite 0.14 allows directly accessing the ORGANSIM subfield. However, this interface retrieves the subfield as plain text, extracting the phylogenetic classifications is up to the user

**Comment by padix-key** [comment]
Since there are multiple schemes for phylogenetic classification, there is no clear solution for the demanded functionality. Please use the low-level API to extract the `ORGANSIM` subfield and parse the content with a custom function.
