### ISSUE TITLE
xtc reader throws memory error even though it shouldn't

### ISSUE THREAD

**Issue by danijoo** [biotite-dev/biotite#111]
The xtc input reader intrinistically checks if the read in trajectory fits into memory before loading it - and throws a MemoryError if it does not fit. However, this check also fails when loading only parts of a trajectory:

```python
import biotite.structure.io.xtc as xtc
f = XTCFile()

# this fails correctly because the file is too large
f.read("md.xtc")

# this should not fail because an xtc reduced to every10th frame works - but it does
f.read("md.xtc", step=10) 

# also fails even though it only loads 10 models!
f.read("md.xtc", stop=10) 
```

**Comment by danijoo** [comment]
related: mdtraj/mdtraj#1458

**Comment by padix-key** [comment]
As you pointed out in mdtraj/mdtraj#1458, this is an issue with MDTraj. Hence I am not able to fix it in the Biotite code. However, I will keep this issue open until the issue in resolved in MDTraj.

**Comment by padix-key** [comment]
You can now supply the `chunk_size` parameter to the `read()` method in order to resolve these memory issues
