### ISSUE TITLE
Add support for hybrid serial numbers in PDB format?

### ISSUE THREAD

**Issue by danijoo** [biotite-dev/biotite#112]
The current limitation of the pdb format is that it only supports serial numbers up to 99999 atoms and 9999 residues. An enhanced version of the pdb format called "hybrid-36 pdb" overcomes this by switching to a hex representation for those ids. 

Example
base pdb format
```
ATOM      1  O           1       0.251  -0.360  -0.046  1.00  0.00
ATOM      2  H           1       0.249   0.684   0.231  1.00  0.00
ATOM      3  H           1       0.586  -0.954   0.791  1.00  0.00
...
ATOM  99997  O           1       0.251  -0.360  -0.046  1.00  0.00
ATOM  99998  H           1       0.249   0.684   0.231  1.00  0.00
ATOM  99999  H           1       0.586  -0.954   0.791  1.00  0.00
ATOM      1  O           1       0.251  -0.360  -0.046  1.00  0.00
ATOM      2  H           1       0.249   0.684   0.231  1.00  0.00
ATOM      3  H           1       0.586  -0.954   0.791  1.00  0.00
```

hybrid-36 pdb
```
ATOM      1  O           1       0.251  -0.360  -0.046  1.00  0.00
ATOM      2  H           1       0.249   0.684   0.231  1.00  0.00
ATOM      3  H           1       0.586  -0.954   0.791  1.00  0.00
...
ATOM  99997  O           1       0.251  -0.360  -0.046  1.00  0.00
ATOM  99998  H           1       0.249   0.684   0.231  1.00  0.00
ATOM  99999  H           1       0.586  -0.954   0.791  1.00  0.00
ATOM  A0000  O           1       0.251  -0.360  -0.046  1.00  0.00
ATOM  A0001  H           1       0.249   0.684   0.231  1.00  0.00
ATOM  A0002  H           1       0.586  -0.954   0.791  1.00  0.00
```

As you can see, the big advantage of this format is that it keeps backward compatibility if the residue and serial id are below the threshold for hex numbers - which is a clear advantage over other efforts to overcome the limitations of pdb.

This format was recently implemented in Modeller 9.22 and is also available an various other software packages like MDAnalysis. I think an implementation of this for biotite would not require a lot of code changes: The pdb reader can do this internally when parsing the serial and residue field. And for output, it could be either a modified version of PDBFile or a simple flag to alter the output numbering.

I'd like to put this up for diskussion here before making the effort to implement it. What's your opinion? Yay or nay ;)

**Comment by padix-key** [comment]
I think this is a useful contribution to the `PDBFile` class. I imagine, that the user can turn this mode on by setting a new `hybrid36` parameter in the `set_structure()` method to `True`. One issue I see is the performance: The integer conversion used at this point is fast, as Python implements it as C-function.
Therefore, I think the hybrid36-to-int and the int-to-hybrid36 conversion functions need to be implemented in Cython in order to retain the performance.

**Comment by padix-key** [comment]
Using a memory view of the hybrid36-string the implementation in Cython is probably relatively simple:
https://cython.readthedocs.io/en/latest/src/tutorial/strings.html#accepting-strings-from-python-code
