### ISSUE TITLE
structure.rmsd() should support ndarray as input

### ISSUE THREAD

**Issue by frantropy** [biotite-dev/biotite#146]
structure.rmsd() supports AtomArrays as input for the reference and subject. It should support ndarrays as well, making it easier to use with PDBFile().get_coord.

**Comment by danijoo** [comment]
I agree. I think every function that can trivially support coords instead of `AtomArray` should do so.

**Comment by padix-key** [comment]
You are right. I will prepare a PR for this issue.

**Comment by padix-key** [comment]
Fixed by #147
