### ISSUE TITLE
pdb.get_structure should throw an error for unknown extra fields

### ISSUE THREAD

**Issue by danijoo** [biotite-dev/biotite#162]
Hi,

```Python
import biotite.structure.io as io
s = io.load_structure("1l2y.pdb", extra_fields="asdasd")
s.asdasd
> AttributeError: 'AtomArray' object has no attribute 'asdasd'
```

In the above example, `load_structure` does not throw an error for the passed extra_field even though its not a valid one. I think an error thrown during load_structure would be a nicer way to handle this because the caller immediately knows something went wrong.\

**Comment by danijoo** [comment]
I prepared a branch that changes this behaviour and throws a value error on an extra field. Let me know what you think about this.

**Comment by padix-key** [comment]
I agree with you. Feel free to create a PR with you branch. I think this issue should be solved on the level of the individual file readers, in this case the `PDBFile` class.
