### ISSUE TITLE
Shifted atom coordiantes when parsing single models from MMTF

### ISSUE THREAD

**Issue by LeeryScientist** [biotite-dev/biotite#205]
Can occur for some models, if the models in the file have unequal amount of atoms and I have to parse single models. As far as I can tell, the first model is always parsed properly.
It looks like atom coordinates from the last residues appear in the first one and all other atom coordinates are shifted further back in the `AtomArray`. When exporting the models back into a file and looking at them in Chimera, the wrong atoms are bonded to each other.

Examples
- 2axd
- 1iey
- 1jy6

**Comment by padix-key** [comment]
I can confirm this issue:
```python
MODEL = 2
pdbx_file = pdbx.PDBxFile.read(rcsb.fetch("2axd", "cif"))
mmtf_file = mmtf.MMTFFile.read(rcsb.fetch("2axd", "mmtf"))
pdbx_structure = pdbx.get_structure(pdbx_file, model=MODEL)
mmtf_structure = mmtf.get_structure(mmtf_file, model=MODEL)
assert np.allclose(pdbx_structure.coord, mmtf_structure.coord)

```
ValueError: operands could not be broadcast together with shapes (1277,3) (1276,3) 
```

The atom coordinates are not only shifted, but there is also a missing atom in the structure parsed from MMTF.

**Comment by padix-key** [comment]
Thanks for reporting. The models should be loaded properly from MMTF files in the upcoming release.
