### ISSUE TITLE
Writing mmcif (pdbx) files needs whitespace at the end of _atom_site labels

### ISSUE THREAD

**Issue by zeynepabali** [biotite-dev/biotite#224]
In PDB mmcif files have a single white space at the end of _atom_site labels. Not having these white spaces makes the cif files created using biotite, sometimes results in errors in some other programs (MMAlign, TMAlign as far as I know). Just adding that space at the end of the label solves the problem.

**Comment by padix-key** [comment]
Do you mean for example `'_atom_site.group_PDB '` in files created by the PDB in contrast to  `'_atom_site.group_PDB'` in files created by Biotite?

**Comment by zeynepabali** [comment]
Yes, exactly.

**Comment by padix-key** [comment]
Okay, this should be quite easy to fix. Thanks for reporting.

**Comment by padix-key** [comment]
I prepared a PR. The following CIF file was created after the fix. Does it work for you?
[test.txt](https://github.com/biotite-dev/biotite/files/5037023/test.txt)

**Comment by zeynepabali** [comment]
Thank you. Yes, this is working.
