### ISSUE TITLE
Incongruent model IDs for Structure files that don't begin with model ID 1

### ISSUE THREAD

**Issue by LeeryScientist** [biotite-dev/biotite#227]
As of now, I only detect this kind of file when parsing model by model
was needed due to the models having an unequal amount of atoms.

There are different behaviors for Biotite's parsers.

The PDB and MMTF parsers treat files as though their first model ID is 1, i.e.,
when passing a model ID to `pdb.get_structure` and `mmtf.get_structure`, it will be
treated as an ordinal number, e.g., ID 7 gets the 7th model, no matter what its
actual ID is.
When using a model ID that goes over the total model count, the corresponding
`ValueError` is issued:
"The file has n models, the given model m does not exist"
This is correctly showing the number of models in the file.

The PDBx parser treats files as though they have as many models as the highest
model ID suggests.
The model ID passed to `pdbx.get_structure` is not treated as an ordinal, but as
an actual model ID, e.g., in a file that has models 21 to 40, passing 1 to 20 
for the model ID will return empty `AtomArray` instances, while the present 
models can be reached by their corresponding IDs.
When using a model ID that goes over the highest model ID, again the
`ValueError` is issued, but with n not standing for the actual count of models, 
but for the highest model ID.

Since I'm building an MMTF database based on PDBx files, I can't safely use the
model IDs inferred while parsing.
For now I'm building a blacklist of PDB IDs, but I don't know if there are
problematic files that I'm not catching with my current method.
For my use case, it would be preferable if all parsers behaved like the PDBx
parser.

On a related note, there are two things that I would find useful, that I 
currently don't know how to do with Biotite:
- Read out the available model IDs of a file before parsing a model from it
- Attach a model ID attribute to `AtomArray` instances upon parsing

Examples (model IDs):
- 1crr (21 to 40)
- 1ezc (18 to 34)
- 1ezd (35 to 50)

**Comment by padix-key** [comment]
This is interesting, I was not aware that there are structures in the PDB, where the model ID does not start at `1`. Would it also be reasonable, if the PDBx parser behaved like the PDB and MMTF one?


> Read out the available model IDs of a file before parsing a model from it

You could use the low level PDBx API, for example `np.unique(pdbx_file["atom_site"]["pdbx_PDB_model_num"].astype(int))` should do the trick here

> Attach a model ID attribute to AtomArray instances upon parsing

You can attach the model ID after parsing:
```
structure.add_annotation("model_id", int)
structure.model_id[:] = 1
```
However, this does not work meaningfully for `AtomArrayStack` objects, since the annotation arrays correspond to all models.

**Comment by LeeryScientist** [comment]
> Would it also be reasonable, if the PDBx parser behaved like the PDB and MMTF one?

This would also be alright. It's mostly important that model IDs stay the same between parsers.

**Comment by padix-key** [comment]
I merged the fix for this. Thank you for reporting.
