### ISSUE TITLE
Using 'hbond()' on structures without hydrogen

### ISSUE THREAD

**Issue by entropybit** [biotite-dev/biotite#241]
When using hbond on a structure where no hydrogen atoms have been added an error should be thrown, informing you
of the total absence of hydrogen. 
This is not the case, as can be seen, e.g., using hbond on https://www.rcsb.org/structure/1E7U.

**Comment by padix-key** [comment]
This PR adds a warning, that is raised if the input structure does not contain hydrogen atoms. An error would be too 'hard' in my opinion, as molecules without hydrogen atoms are still valid molecules (e.g. CO2), but simply do not have hydrogen bonds.
