### ISSUE TITLE
temp file in windows in biotite/application/msaapp.py

### ISSUE THREAD

**Issue by andrew-torda** [biotite-dev/biotite#243]
Under windows (10) 
in src/biotite/application/msaapp.py
There is a line
        self._out_file    = NamedTemporaryFile("r", suffix=".fa")
This should be 
        self._out_file    = NamedTemporaryFile("w+t", suffix=".fa", delete=False)
otherwise one gets a permission denied error. Of course this means the file will not automatically be deleted, so in the function cleanup() near line 155, 
        self._in_file.close()
should be something like
        self._in_file.close()
        os.remove(self.get_output_file_path())

I don't know if this will cause tears under linux and I see that you lose the elegance of having a file automatically deleted.

**Comment by padix-key** [comment]
I'll have a look into it. Thank you.

**Comment by padix-key** [comment]
Could you post the traceback of the `IOError`? Which MSA program did you use? Maybe there is another solution to it, than setting `delete` to `False`.

**Comment by andrew-torda** [comment]
What a swift reply.
We will try to get a traceback.
The error occurs with both clustalo and mafft and is provoked when `evaluate()` calls `open(self.get_output_filepath())`, so it probably happens with muscle as well.

**Comment by pauline-busch** [comment]
![MafftBUG (errno13) in app py](https://user-images.githubusercontent.com/73955451/98135579-44b1f700-1ec0-11eb-8d90-2a50858360c1.PNG)

**Comment by pauline-busch** [comment]
Exception has occurred: PermissionError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
[Errno 13] Permission denied: 'C:\\Users\\Rickman\\AppData\\Local\\Temp\\tmpbjgdjob7.fa'
  File "C:\Python38\Lib\site-packages\biotite\application\mafft\app.py", line 79, in evaluate
    with open(self.get_output_file_path(), "w") as f:
  File "C:\Python38\Lib\site-packages\biotite\application\application.py", line 153, in join
    self.evaluate()
  File "C:\Python38\Lib\site-packages\biotite\application\application.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "C:\Python38\Lib\site-packages\biotite\application\msaapp.py", line 400, in align
    app.join()
  File "C:\Users\Rickman\Labrotation\Debug\DebugMafft.py", line 18, in <module>
    alignment = mafft.MafftApp.align(sequences, bin_path='C:/Users/Rickman/Downloads/mafft-7.471-win64-signed/mafft-win/mafft.bat', matrix=matrix)
  File "C:\Python38\Lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Python38\Lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Python38\Lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Lib\runpy.py", line 194, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,

**Comment by padix-key** [comment]
I was able to reproduce this error on Windows with the following snippet:

```python
import biotite.application.mafft as mafft
import biotite.sequence as seq

seq1 = seq.ProteinSequence("BIQTITE")
seq2 = seq.ProteinSequence("TITANITE")
seq3 = seq.ProteinSequence("BISMITE")
seq4 = seq.ProteinSequence("IQLITE")
mafft_path = r"C:\Users\Padix\Downloads\mafft-7.471-win64-signed\mafft-win\mafft.bat"
app = mafft.MafftApp([seq1, seq2, seq3, seq4], bin_path=mafft_path)
app.start()
app.join()
alignment = app.get_alignment()
print(alignment)
```

Error traceback:
```
PermissionError                           Traceback (most recent call last)
<ipython-input-9-13ab49946e2f> in <module>
      9 app = mafft.MafftApp([seq1, seq2, seq3, seq4], bin_path=mafft_path)
     10 app.start()
---> 11 app.join()
     12 alignment = app.get_alignment()
     13 print(alignment)

~\anaconda3\envs\biotite-dev\lib\site-packages\biotite\application\application.py in wrapper(*args, **kwargs)
     56                     f"but {app_state} state is required"
     57                 )
---> 58             return func(*args, **kwargs)
     59         return wrapper
     60     return decorator

~\anaconda3\envs\biotite-dev\lib\site-packages\biotite\application\application.py in join(self, timeout)
    151         time.sleep(self.wait_interval())
    152         try:
--> 153             self.evaluate()
    154         except AppStateError:
    155             raise

~\anaconda3\envs\biotite-dev\lib\site-packages\biotite\application\mafft\app.py in evaluate(self)
     77 
     78     def evaluate(self):
---> 79         with open(self.get_output_file_path(), "w") as f:
     80             # MAFFT outputs alignment to stdout
     81             # -> write stdout to output file name

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Padix\\AppData\\Local\\Temp\\tmp1mmdnf3p.fa'
```

**Comment by padix-key** [comment]
I did some research and It seems, you are right: While UNIX systems allow to reopen a `NamedTemporyFile` by its name while it is still open, this does not work on Windows. For reference (https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile):

> Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows NT or later).

The only solution seems to be setting `delete` to `False` and cleaning up the file manually later (e.g. https://bugs.python.org/issue14243).

**Comment by padix-key** [comment]
I prepared a PR based on your proposal. Basically all `NamedTemporaryFile` objects in `biotite.application` are now handled the following way:
```python
temp_file = NamedTemporaryFile(delete=False)

# Do some stuff with the file

temp_file.close()
os.remove(temp_file)
```
