### ISSUE TITLE
Charge annotation's data type incorporated in 'structure.info.residue' is a tuple with the elements as string

### ISSUE THREAD

**Issue by jacob-no-cop** [biotite-dev/biotite#254]
Peculiarly, the data type of the charge annotation delivered by  the function 'structure.info.residue' is a tupel instead of a NumPy array, and the individual elements are strings. One would expect the charge annotation to be a NumPy array and the individual elements to be integers.

```python
fluoromethane = info.residue("CF0")
fluoro_charges = fluoromethane.charge
print(fluoro_charges)
```

The result is a tuple with strings as elements.

**Comment by padix-key** [comment]
Thank you for the report. The output is indeed not intended.
