### ISSUE TITLE
"biotite.structure.connect_via_distances" doesn't register peptide bonds

### ISSUE THREAD

**Issue by jacob-no-cop** [biotite-dev/biotite#266]
"biotite.structure.connect_via_distances" seems to have difficulties registering bonds between individual residues. In this example, it is a peptide bond, i. e. the bond linking two amino acids. The first two residues of the mini protein 1l2y (asparagine and leucine) are extracted, hydrogen atoms are removed and their BondList is printed out based on "connect_via_distances":

>>> file_path = rcsb.fetch("1l2y", "pdb")
>>> pdb_file = PDBFile.read(file_path)
>>> mini_protein = get_structure(pdb_file, model = 1)
>>> mini_protein.bonds = connect_via_distances(mini_protein)
>>> bond_list = mini_protein.bonds
>>> first_res = mini_protein[0:16]
>>> second_res = mini_protein[16:35]
>>> res_one_and_two = first_res + second_res
>>> res_one_and_two_without_hyd = res_one_and_two[res_one_and_two.element != "H"]
>>> carbon_index_of_asn = np.where(res_one_and_two.atom_name == "C")[0][0]
>>> print(carbon_index_of_asn)

2

>>> nitr_index_of_leu = np.where(res_one_and_two_without_hyd.atom_name == "N")[0][1]
>>> print(nitr_index_of_leu)

8

>>> print(res_one_and_two_without_hyd.bonds)

[[ 0  1  0]
 [ 1  2  0]
 [ 2  3  0]
 [ 1  4  0]
 [ 4  5  0]
 [ 5  6  0]
 [ 5  7  0]
 [ 8  9  0]
 [ 9 10  0]
 [10 11  0]
 [ 9 12  0]
 [12 13  0]
 [13 14  0]
 [13 15  0]]

The peptide bond, i. e. the bond between the carbon atom of the hydroxyl group of residue 1 (asparagine) and the nitrogen atom of the amino group of residue 2 (leucine) does not occur in the BondList (the entry [2 8 0] can't be found), which must be a mistake.

**Comment by padix-key** [comment]
The problem is, that the two residues are separated into two `AtomArray` objects, as explained in #269.
