### ISSUE TITLE
"biotite.structure.io.mmtf.get_structure" doesn't register peptide bonds

### ISSUE THREAD

**Issue by jacob-no-cop** [biotite-dev/biotite#269]
Similar to "biotite.structure.connect_via_distances", "biotite.structure.io.mmtf.get_structure" seems to have difficulties registering bonds between individual residues. The example is exactly the same as in issue #266:

import biotite.database.rcsb as rcsb
from biotite.structure.io.mmtf import MMTFFile
from biotite.structure.io.mmtf import get_structure

file_path = rcsb.fetch("1l2y", "mmtf")
mmtf_file = MMTFFile.read(file_path)
mini_protein = get_structure(pdb_file, model = 1, include_bonds=True)
first_res = mini_protein[0:16]
second_res = mini_protein[16:35]
res_one_and_two = first_res + second_res
res_one_and_two_without_hyd = first_res_without_hyd + \
   second_res_without_hyd
print(res_one_and_two_without_hyd.bonds)

[[ 0  1  1]
 [ 1  2  1]
 [ 2  3  2]
 [ 1  4  1]
 [ 4  5  1]
 [ 5  6  2]
 [ 5  7  1]
 [ 8  9  1]
 [ 9 10  1]
 [10 11  2]
 [ 9 12  1]
 [12 13  1]
 [13 14  1]
 [13 15  1]]

Here again, the bond [2 8 1] representing the bond between the nitrogen atom of the amino group of the first residue and the carbon atom of the carboxyl group of the second residue is missing, which must be a mistake.

**Comment by padix-key** [comment]
The problem is that you separate the first and second residue into two individual `AtomArray` objects. These two atom arrays do not *have knowledge* of each other, so the peptide bond connecting them is severed. If you merge them again, the peptide bond is already lost.

If you keep both residues together from the beginning the peptide bond appears as expected:
```python
file_path = rcsb.fetch("1l2y", "mmtf")
mmtf_file = mmtf.MMTFFile.read(file_path)
mini_protein = mmtf.get_structure(mmtf_file, model = 1, include_bonds=True)
res_one_and_two = mini_protein[0:35]
for i, j, _ in res_one_and_two.bonds.as_array():
    if res_one_and_two.res_id[i] != res_one_and_two.res_id[j]:
        print(res_one_and_two[i])
        print(res_one_and_two[j])
        print()
```

```
    A       1  ASN C      C        -7.117    2.964   -1.897
    A       2  LEU N      N        -6.379    4.031   -2.228
```

**Comment by jacob-no-cop** [comment]
Thank you for your answer.
