### ISSUE TITLE
RCSB fasta fetch tries to use a removed api

### ISSUE THREAD

**Issue by danijoo** [biotite-dev/biotite#272]
It seems like rcsb fasta fetch api has been removed/replaced by a new one on 9. Dec. Biotite still uses the old api and therefore fails to return a correct fasta file, but writes the HTML error page to the file instead:

Minimal working code:
```python
# download fasta
import biotite.database.rcsb as rcsb
file = rcsb.fetch("5u6p", "fasta", ".", overwrite=True, verbose=True)
# Fetching file 1 / 1 (5u6p)...
# Done
```
The resulting 5u6p.fasta contains no fasta, but a html file:
```python
# reading file content
open("./5u6p.fasta", "r").read()
#'<!DOCTYPE html><html lang="en"><head><script src=.....<lots of more stuff..>.'
```

Opening the file with a webbrowser reveals the following content:
```
We're sorry, the page you requested is unavailable:
http://www.rcsb.org/pdb/download/downloadFastaFiles.do?structureIdList=5u6p&compressionType=uncompressed

It has been permanently removed as part of our announced shutdown on December 9th, 2020.

See the Legacy API Shutdown December 9 announcement for further details.
```

**Comment by padix-key** [comment]
Which Biotite version did you use? Since Biotite 0.24 `rcsb.fetch()` should use the new FASTA fetch API.

**Comment by danijoo** [comment]
indeed :)
