### ISSUE TITLE
NetworkX for resolving conflicting pseudoknot cliques

### ISSUE THREAD

**Issue by padix-key** [biotite-dev/biotite#289]
With *NetworkX* becoming a *Biotite* dependency in the next update (#283), we could think about replacing the functions for resolving conflicting regions in `biotite.structure.pseudoknots()` with graph based solutions:

- `_find_non_conflicting_regions()` -> `networkx.isolates()`
- `_conflict_cliques()` -> `networkx.connected_components()`

This could make the code cleaner and even increase the performance (although this need to be tested).

@tomtomhdx What is your opinion about this?

**Comment by tomtomhdx** [comment]
This sounds like an excellent idea!

I will make the adjustments and check whether the performance increases.
