### ISSUE TITLE
String representation of objects 

### ISSUE THREAD

**Issue by Gizzio** [biotite-dev/biotite#290]
It would be nice if we could add the `__repr__` method to biotite objects such as sequences, etc. Representations are especially useful when working in Jupiter notebook.

**Comment by Gizzio** [comment]
I think the first for `AtomArray` is more intuitive.
As for sequences, I agree with your proposition.

**Comment by freezer3** [comment]
I agree with Gizzio, such a method would be very helpful in my analysis

**Comment by MaxGreil** [comment]
After talking to @padix-key , this would be the target classes (for now):

Sequence subpackage:

- [ ] Sequence
- [ ] NucleotideSequence
- [ ] ProteinSequence
- [ ] GeneralSequence
- [ ] Alphabet
- [ ] LetterAlphabet
- [ ] CodonTable
- [ ] Alignment
- [ ] SubstitutionMatrix
- [ ] Location
- [ ] Feature
- [ ] Annotation
- [ ] AnnotatedSequence

Structure subpackage:

- [ ] Atom
- [ ] AtomArray
- [ ] AtomArrayStack

I will have a look at it.

**Comment by padix-key** [comment]
I reopened the issue, as the closing PR #299 from @MaxGreil only covered only a part of the classes listed above.

**Comment by MaxGreil** [comment]
@padix-key I will have a look at the remaining classes
