### ISSUE TITLE
FastaFiles should accept Sequence 

### ISSUE THREAD

**Issue by Gizzio** [biotite-dev/biotite#292]
https://github.com/biotite-dev/biotite/blob/c8046d5e2fbc943aa3e0d353d5678907487f066a/src/biotite/sequence/io/fasta/file.py#L106
There is a check if FastaFile value is `str`. Shouldn't FastaFile accept Sequence as value? It would code if we use biotite Sequence methods such as `complement()`.

**Comment by padix-key** [comment]
The `FastaFile` class represents the low-level interface to FASTA files
working only with strings. However, the function
`sequence.io.fasta.set_sequence()` stores a `Sequence` object in a
`FastaFile`.

**Comment by padix-key** [comment]
Did my suggestion solve your problem?

**Comment by padix-key** [comment]
I will close this issue now. If the problem still persists, feel free to reopen it.
