### ISSUE TITLE
align_vectors() raises a DeprecationWarning

### ISSUE THREAD

**Issue by padix-key** [biotite-dev/biotite#295]
Sometimes `structure.align_vectors()` raises a `DeprecationWarning`:

```
DeprecationWarning: setting an array element with a sequence. This was supported in some cases where the elements are arrays with a single element.
```

The statement that causes this issue is:

 https://github.com/biotite-dev/biotite/blob/fa7c435d7eca975740fd0a243ab6449da9107df7/src/biotite/structure/transform.py#L357-L361

The reason is that `0` has not the same dimensions as for example `-v[..., 2]`.

**Comment by claudejrogers** [comment]
From reading the docs, it seems like the `structure.align_vectors` function is used for two things: (1) aligning subsections of two molecules (the docstring), or (2) aligning a subsection of a molecule to the x, y, or z axis. For both applications, I would recommend using the Kabsch algorithm to do the rotation/translation.

To that end, a superimpose function that took a molecule, a target subsection, and the corresponding molecule subsection and returned `((molecule.coord - COM_ms) @ U) - COM_t`, where COM_ms and COM_t are the centroids for the subsections and U is the rotation matrix from Kabsch would be nice. Alternatively, it would be nice `superimpose` took a `key` keyword argument (like sort), so users could define subsection masks:

  ```python
>>> # define a key function to select CA and CB atoms from both input structures
>>> superimpose(
...     fixed,
...     mobile,
...     atom_mask=None,
...     key=lambda obj: ((obj.atom_name == "CA") | (obj.atom_name == "CB"))
... )
```

For aligning to molecules to axes, a function (e.g., `align_to_axis(molecule, subsection, axis=2, translate=False)`) that aligns the subsection principal components to the indicated axis could do the job and save end users some code. 

If this is of interest I could submit a pull request.

**Comment by padix-key** [comment]
Hi, thanks for the comment. `structure.align_vectors()` finds the rotation matrix that superimposes a single vector onto another vector and applies this rotation matrix to the given atoms. Although I agree that the Kabsch algorithm implemented in `structure.superimpose()` can achieve this, I think that this approach (calculating covariance matrix, singular value decomposition) is too much calculation effort (although I have no benchmark), since Kabsch minimizes the RMSD for superimpositions with multiple vectors.

For your second part, I think [structure.superimpose_apply()](https://www.biotite-python.org/apidoc/biotite.structure.superimpose_apply.html#biotite.structure.superimpose_apply) fits the requirements, if I understand you correctly. It allows the user to apply the rotation matrix and translation vectors from a prior `superimpose()` call to another `AtomArray`.
However, I just saw that there is no code example in the docstring of `superimpose_apply()` that demonstrates this application.

Your proposition for a function for aligning principal components of a molecule's coord to an axis sounds useful, though I would choose a function name that reflects, that the prinicipal component is aligned to an axis. Maybe its also useful to separate this functionality into two functions: The one you described and one that returns the principal components and is called by the first one.
I already ran multiple times into the problem, your proposed function would solve, and used *SciPy* as solution, for example

https://www.biotite-python.org/examples/gallery/structure/peoe_visualization.html#sphx-glr-examples-gallery-structure-peoe-visualization-py

```python
pca = PCA(n_components=3)
pca.fit(molecule.coord)
molecule = struc.align_vectors(molecule, pca.components_[-1], [0, 0, 1])
```

However, since *SciPy* is not a dependency of *Biotite*, the principal component analysis from *SciPy* cannot be used for a function in *Biotite*.
Would your PR include the principal component calculation?

**Comment by padix-key** [comment]
This solution looks good to me, though I think some comments would be helpful to explain the purpose of the linear algebra operations. Could you open a PR? Then we could discuss some details in the new thread.

**Comment by claudejrogers** [comment]
Back to the original issue of the depreciation warning, it seems like is could only happen, and still have the rest of the code work, if the `origin_direction` and/or `target_direction` had an extra dimension (e.g.,`np.random.rand(1, 3)`). 

Since the docs say the shape of  `origin_direction` and `target_direction` should be `(3,)`, you could check the shape of the inputs and raise a `ValueError` if the shape is wrong, or call `np.squeeze` on the arrays to get rid of the extra dimensions.

This would ensure `v.shape == (3,)` and the matrix `v_c` could be declared:

```python
vx, vy, vz = np.cross(origin_direction, target_direction)
v_c = np.array([
    [  0, -vz,  vy],
    [ vz,   0, -vx],
    [-vy,  vx,   0]
], dtype=float)
```

I could submit a pull request.
