### ISSUE TITLE
io.load_structure filter template for atom_i

### ISSUE THREAD

**Issue by danijoo** [biotite-dev/biotite#308]
The `atom_i` parameter of `biotite.structure.io.xtc.XTCFile.read` allows to only read a subset of atoms into memory. If the trajectory is read via `io.load_structure(trj, template)`, this argument is not properly applied since the template is not filtered beforehand, leading to the following error:

Example:
```python
import biotite.structure.io as io
s = io.load_structure("nvt.xtc", "nvt.gro", atom_i=[1,2])
# ValueError: Template has 196252 atoms, but 2 coordinates are given
```

To work around this, the template must be filtered manually. I.e. this snippet works:
```python
import biotite.structure.io as io
s = io.load_structure("nvt.gro")
s = s[[1,2]]
s = io.load_structure("nvt.xtc", template=s, atom_i=[1,2])
```

This is a bit clumsy and also not intuitive to fix for a user that is not familiar with the underlying code of biotite. Maybe we can make it so that the atom_i filter is automatcally applied to the template if `atom_i.shape != template.shape` ? What do you think?

**Comment by padix-key** [comment]
> Maybe we can make it so that the atom_i filter is automatcally applied to the template if atom_i.shape != template.shape

This sounds like a sensible solution.

**Comment by padix-key** [comment]
In case you are preparing a PR, could you mention this new behavior in the `Notes` section of the docstring?
