### ISSUE TITLE
Spacing in Alignments

### ISSUE THREAD

**Issue by neulig** [biotite-dev/biotite#360]
In alignments of all kind it would help very much if one could insert spacings. This gives a better overview and helps with finding e.g. specifc amino acid residues.
For protein sequences for example a spacing after every 10 amino acids is appropiate. For nucleic acid sequences a spacing after 9 bases helps to keep it in parallel with the open reading frame.

**Comment by padix-key** [comment]
Thank you for the report. I think an optional parameter `symbol_spacing` (or a similar name) would be appropriate for `sequence.graphics.plot_alignment()` and its derived functions. This gives the user the flexibility to set the desired spacing.
