### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by jacob-no-cop** [biotite-dev/biotite#362]
Hello,

Biotite's function "biotite.structure.io.load_structure" raises a ModuleNotFoundError when trying to load a trajectory from a MD simulation to an AtomArrayStack, indicating a dependency must be added.

To be more precise, the following error message appeared: " ModuleNotFoundError: No module named 'mdtraj' "

Hence, mdtraj must be added as dependency.

I executed the following code:

import biotite.structure as struc
traj_file_path = "paromo_fit.xtc"
templ_file_path = "Paromomycin.gro"

template = struc.io.load_structure(templ_file_path)

trajectory = struc.io.load_structure(
    traj_file_path,
    template=template
)

Unfortunately, GitHub does not support the types of the respective files, which is why I can't attach them.

Regards

**Comment by padix-key** [comment]
Hi, since `MDTraj` is only used for reading and writing trajectory files and is otherwise a relatively large package, it is treated as optional dependency (refer to https://www.biotite-python.org/install.html).

Therefore, you need to install `MDTraj` separately, either via
```
pip install mdtraj
```
or
```
conda install -c conda-forge mdtraj
```
