### ISSUE TITLE
PDB element symbol should be guessed from atom name if not present

### ISSUE THREAD

**Issue by danijoo** [biotite-dev/biotite#37]
Strictly speaking, the elemet in a PDB structure (column 77-78) is part of the format specification and should always be set. Nevertheless, a lot of programs ignore this column and omit it in the output or only write it for backbone atoms leading to this column be only partially filled (happened to us). 

Biotite on the other hand, requires this column for various functions including selection of atoms by their types which leads to an Error when these functions are called. The circumstance that this column is often not set can be worked arround by trying to guess the element from the the atom column (line 13-16), possibly in combination with a warning to the user. 
If you are interested in a solution like that, I can make a pull request for this.

**Comment by padix-key** [comment]
I would appreciate, If you create a PR for this. I propose that the guess is performed after the parsing loop, if the the `element` annotation array is completely empty.

**Comment by padix-key** [comment]
Resolved by #38.
