### ISSUE TITLE
biotite.structure.io.save_structure doesn't generate same output for an xtc frame as gromacs

### ISSUE THREAD

**Issue by entropybit** [biotite-dev/biotite#376]
If I load an xtc file in biotite and output the first frame as a single PDB like this:

```python
templ_file_path = "md_input.pdb"
template_model = strucio.load_structure(templ_file_path)
traj_file_path = "nopbc_cluster_fit.xtc"
protein = strucio.load_structure(templ_file_path)
protein_mask = struc.filter_amino_acids(protein)
template = protein[protein_mask]

print(" .. loading trajectory ...")
xtc_file = xtc.XTCFile()
xtc_file.read(traj_file_path, atom_i=np.where(protein_mask)[0], stop=10)
time = xtc_file.get_time()
time = 10**(-3)*time

trajectory = xtc_file.get_structure(template)

strucio.save_structure("frame_0_biotite.pdb", trajectory[0])
```

the resulting PDB files differs from one generated by using gromcs like this:

```bash
gmx trjconv -s md.tpr -f nopbc_cluster_fit.xtc -b 0 -e 0 -o frame_0.pdb
```

Speciffically both pdbs seem differnt when loaded in pymol (the one generated with biotite seems broken even after
doing dss), as illustrated in the following example (in white the one generated with gromacs, in red the one generated with
biotite).

![broken](https://user-images.githubusercontent.com/10496600/159165705-ae9b3748-212f-4886-a218-9acf394761b2.png)
![whole](https://user-images.githubusercontent.com/10496600/159165706-7522cfed-f7c8-43e5-96e6-6019c9d9cd28.png)

**Comment by padix-key** [comment]
Hi, could you link or send me both, the output PDB generated by Biotite and by Gromacs `trjconv`? Then I could look were the difference and possible error is. It would be even more helpful, if could also send me the input trajectory and PDB.

**Comment by entropybit** [comment]
zulip^^

**Comment by padix-key** [comment]
I checked your files and it seems like `md_input.pdb` and the trajectory have not the same atom order. Therefore, the atoms get the wrong coordinates assigned which seems to cause *PyMOL* not recognizing the model as connected protein chain.
Using an input *.gro* from `gmx grompp` or an output *.gro* from `gmx mdrun` from the simulation as the trajectory should solve this problem.
