### ISSUE TITLE
sequence and secondary structure representation

### ISSUE THREAD

**Issue by diffracteD** [biotite-dev/biotite#384]
Hi,

I was going through your wonderful code recently (https://www.biotite-python.org/examples/gallery/structure/transketolase_sse.html). It is really great way to represent 2D secondary structure. However, I couldn't stop wondering that is there a way to display the sequence too at the bottom of every secondary structure line ? This would make the representation complete and also provide easy comparison options.

Please advise.
Thanks.

**Comment by padix-key** [comment]
I recently created example code that combines mixed multi-row plots for #383. You could replace the alignment plots with plots containing `matplotlib.text.Text` instances for every amino acid in the corresponding sequence segment.
