### ISSUE TITLE
Coloring MSA based on R value or other arbitrary values

### ISSUE THREAD

**Issue by seanrjohnson** [biotite-dev/biotite#403]
Hi,

When drawing MSAs, I'm wondering if there is a way to define colors for each specific position in the MSA. Two use cases I am thinking of are: 

- I have AlphaFold2 structures for a bunch of related sequences. In the pdb files, the pLDDT from AlphaFold is stored as the R value. I know how to use biotite to extract the sequences from the pdb files and do a muscle alignment. I would like to draw that alignment with each residue colored according to its R value (maybe on a gradient from white to red or something like that).
- I've run Rosetta on each of the AlphaFold structures described above, and I've saved the position-wise energies for each structure. I'd like to draw those energies as a gradient on the MSA.

Can you suggest ways to do this?

Thanks

**Comment by padix-key** [comment]
Hi, to achieve this, you have to define your own [LetterPlotter](https://www.biotite-python.org/apidoc/biotite.sequence.graphics.LetterPlotter.html) and simply overwrite `get_color()`, where you would choose the color based on the R value.
I have created a small example that demonstrates this:

https://gist.github.com/padix-key/56b88361cd66ebda2077a8fd2fefb4ea

The result:

![msa](https://user-images.githubusercontent.com/28051833/176713362-7e30fe48-6f56-45ae-b2ce-094c7a217147.png)

But it would probably be also helpful to have such functionality directly integrated in Biotite.

**Comment by seanrjohnson** [comment]
Thanks. That basically solves my issue. I can imagine how it will be possible to write the function I need.
I'll post back here if I run into trouble.

**Comment by seanrjohnson** [comment]
Just to follow up. Starting from the example you posted above, I was able to accomplish what I wanted. As far as I'm concerned you can close the issue.
