### ISSUE TITLE
pdbx get_structure with use_author_fields gives different results

### ISSUE THREAD

**Issue by ebetica** [biotite-dev/biotite#406]
On 7yxg, if we load the CIF file with `pdbx.get_structure(file, use_author_fields=False)` vs `pdbx.get_structure(file, use_author_fields=True)`, we get a different number of atoms. I believe this is because the author residue index is -1 for chain B, whereas the real residue index is not -1.

**Comment by padix-key** [comment]
As no proper solution is in sight, I will close this issue as *wontfix*.
