### ISSUE TITLE
remove incomplete residues

### ISSUE THREAD

**Issue by andreassteffen** [biotite-dev/biotite#431]
Hi,
is there a simple way to remove incomplete amino acid residues, i.e. residues with missing atoms?
Many thanks, Andreas

**Comment by padix-key** [comment]
There is no simple way in terms of a single function, but this can be solved in a small loop:
https://gist.github.com/padix-key/ecd5c5b494242d7eb1c4004e677d8191

The code uses a simple heuristic: If an amino acid has less atoms than the complete reference molecule from the [CCD](https://www.wwpdb.org/data/ccd), the amino acid is removed from the structure.
This heuristic would give erroneous results, if a residue misses one atom but has another additional atom, but I do not know any PDB entry where this case appears.

I expected for your use case that hydrogen atoms are not relevant, hence the filtering for non-hydrogen atoms.

**Comment by andreassteffen** [comment]
thank you ! That worx!
Very nice llibrary indeed!
