### ISSUE TITLE
Potentially wrong angle in `base_stacking()`

### ISSUE THREAD

**Issue by padix-key** [biotite-dev/biotite#432]
In `base_stacking()` one criterion states:

> Angle between normalized distance vector between two ring centers and both bases' normal vectors <=40°

However in the relevant place in the code, the criterion is implemented the following way:

https://github.com/biotite-dev/biotite/blob/60bc7bde993cab5b3f595ebceeca160c8cc47c62/src/biotite/structure/basepairs.py#L1102-L1111

I suspect an error in the angle condition: The one angle (40°) is relevant, if both vectors point approximately in the same direction, and the other one (120°)  is relevant, if both vectors point approximately in opposite direction.
However, I think the desired angle here is 180° - 40° = 140°, instead of 120°. Am I correct here or am I missing something?

**Comment by tomtomhdx** [comment]
@padix-key You are correct. This seems to be a typo. I will prepare a PR with the correct condition.
