### ISSUE TITLE
Parsing error with PDB index beyond "99999"

### ISSUE THREAD

**Issue by heejongkim** [biotite-dev/biotite#456]
Hi,

I'm having an issue with parsing a gigantic pdb file that has more than 99999 ATOM entries.
It emits the error msg starting with A0000 because the index is expected as numeric without any letters.
It would be awesome if it's possible that index can be a little bit more permissive so that this gigantic pdb can be parsed.

Thank you so much for developing such an awesome library.

best,
heejong

**Comment by padix-key** [comment]
Hi, could you share the error output and, if possible, also the PDB file where the error occurs? Normally `PDBFile` should be able to parse *hybrid-36* atom numbers, which start with `A0000`, so you found potentially a bug here.

**Comment by heejongkim** [comment]
Hi,

Sorry for getting back to you late.

The causing line is
https://github.com/biotite-dev/biotite/blob/d632f5036a0fb2d13187b56e37b40b263c6a92e2/src/biotite/structure/io/pdb/file.py#L1052

The error msg is
`ValueError: invalid literal for int() with base 10: 'A0090'`

**Comment by padix-key** [comment]
This seems to be indeed a bug: The *hybrid-36* parsing is properly done for `ATOM` and `HETATM` records, but not for `CONECT` records. I will create a PR fixing this problem.
