### ISSUE TITLE
using Alignment model to get an alignment object artificially

### ISSUE THREAD

**Issue by sirius777coder** [biotite-dev/biotite#462]
Hi,

If I have three sequences, "AGERT","EAEEA","TTGKL", how can I artificially get a meaningless sequence alignment as follow?
AGERT,
EAEEA,
TTGKL,
You can see I just put three sequences together but don't do any other alignment.

**Comment by padix-key** [comment]
Hi. If you have more than two sequences, you have to create an `Alignment` object manually. For this, you need the sequences and the trace, which specifies for each column in the alignment which positions of the sequences are aligned with each other:
```python
import numpy as np
import biotite.sequence as seq
import biotite.sequence.align as align


SEQUENCE_STRINGS = [
    "AGERT",
    "EAEEA",
    "TTGKL"
]

sequences = [seq.ProteinSequence(seq_str) for seq_str in SEQUENCE_STRINGS]
seq_length = len(sequences[0])
n_sequences = len(sequences)
trace = np.tile(np.arange(seq_length), n_sequences) \
          .reshape(n_sequences, seq_length) \
          .transpose()
print("Trace:")
print(trace)
print()
alignment = align.Alignment(sequences, trace)
print("Alignment:")
print(alignment)
print()

# If the alignment score is also required:
alignment.score = align.score(alignment, align.SubstitutionMatrix.std_protein_matrix())
print("Score:")
print(alignment.score)
print()
```

Output:

```
Trace:
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]

Alignment:
AGERT
EAEEA
TTGKL

Score:
-2
```

If you like to have another example for this procedure, have a look at https://www.biotite-python.org/examples/gallery/sequence/anderson_logo.html

**Comment by sirius777coder** [comment]
Really thanks for your timely reply! I just need this script and function to make my sequence logo plot. I love the biotite and your group so much !!!

**Comment by padix-key** [comment]
I am happy to help.
