### ISSUE TITLE
 Issue with Reading PDB Files Using Biotite

### ISSUE THREAD

**Issue by sirius777coder** [biotite-dev/biotite#476]
Dear Biotite team,

I greatly appreciate the Biotite package for computational work in my research. It has been a valuable tool for me. However, I've recently encountered an issue when trying to read certain PDB files that contain different column structures.

For example, I have a PDB file with the following content:
```
HETATM 6484  O   HOH A1137       5.538  27.706  17.391  1.00 52.70           O  
HETATM 6485  O   HOH A1138     -31.621   5.725   7.990  1.00 56.92           O  
HETATM 6486  O   HOH A1139     -10.294 -13.703  18.042  1.00 66.51           O  
HETATM 6487  O   HOH A1140       0.629  25.091  39.437  1.00 57.67           O  
HETATM 6488  O   HOH A1141       9.671  12.984   0.580  1.00 68.79           O  
HETATM 6489  O   HOH A1142      -0.767  26.876  16.651  1.00 57.06           O  
HETATM 6490  O   HOH A1143       6.355  27.752  14.808  1.00 50.32           O  
HETATM 6491  O   HOH A1144       8.233 -11.246  44.294  1.00 66.98           O  
MASTER      349    0   12   11   51    0   19    6 6466    1  195   59                
HETATM    1  N   DUM     1     -36.000  -2.000 -12.500
HETATM    2  O   DUM     2     -36.000  -2.000  12.500
HETATM    3  N   DUM     3     -36.000   0.000 -12.500
HETATM    4  O   DUM     4     -36.000   0.000  12.500
HETATM    5  N   DUM     5     -36.000   2.000 -12.500
```
You can see that the columns in the PDB file are inconsistent. It appears that Biotite is unable to handle these kinds of files currently. Is this considered as a bug? If not, could you please guide me on how to work around this issue using Biotite?

Thank you for your time and support.

Best regards,
Bo

**Comment by padix-key** [comment]
Hi. The lower part of your PDB file (the `DUM` atoms) are missing the B-factor and occupancy columns, which are required by the PDB specification. Hence, I wouldn't consider this a bug in Biotite. I see two possible solutions her. Either you could fill the missing columns in the file with dummy values (e.g `1.00`) or you could modify the source code yourself: The occupancy and B-factor are parsed but not further used when using the default parameters in `pdb.get_structure()`. Hence removing the following lines

https://github.com/biotite-dev/biotite/blob/a2df958cb76e4e7f8734c31e6d0fcd800ba1564b/src/biotite/structure/io/pdb/file.py#L420-L421

in your local Biotite installation should solve the problem.

**Comment by sirius777coder** [comment]
Great, actually I use the function strucio.load_structure() and don't specify the extra_fileds, it seems this function will still load the b_factor column.

**Comment by padix-key** [comment]
Yes, but it will not put it into an annotation array, i.e. `atom_array.b_factor` will not exist unless it is specified in the `extra_fields`.

**Comment by sirius777coder** [comment]
Get it! Thanks so much
