### ISSUE TITLE
GenBank LOCUS parser is overly restrictive on the locus id

### ISSUE THREAD

**Issue by tfenne** [biotite-dev/biotite#486]
The GenBank parser, when parsing the LOCUS line, fails with a not-so-helpful error when the ID (string after the LOCUS keyword) is more than 16 characters long.  It appears to include the remainder of the ID, and the spaces, into the next field (length) and then fail to parse the length.

The GenBank format seems ... not super well specified, though I did find references that "strict" GenBank limits the ID to 16 characters.  All the same, I don't think it would hurt to just split on whitespace and take the fields regardless of length.

**Comment by padix-key** [comment]
Hi, sorry for the late answer. I had a look at the parser code I wrote a few years ago and I neither know the reason for the strict limits I implemented. Unfortunately, I have not left a reference where the numbers are taken from. In fact these strict limits do not suffice this [example file](https://www.ncbi.nlm.nih.gov/Sitemap/samplerecord.html) either. Therefore, I would also consider the current behavior a bug.

Whitespace splitting probably should do the job here. I think we can expect that the locus name does not contain whitespace. A circumstance that could be a problem, is that not all fields in the LOCUS field need to be specified, so additional pattern matching of the splitted strings might be necessary. What do you think?

**Comment by tcjaffe** [comment]
From the documentation on that sample record, it looks like the ID was previously limited to 10 characters but has since been expanded. Maybe this code was implemented before the ID expansion?

> The locus name was originally designed to help group entries with similar sequences: the first three characters usually designated the organism; the fourth and fifth characters were used to show other group designations, such as gene product; for segmented entries, the last character was one of a series of sequential integers. (See GenBank [release notes](https://ftp.ncbi.nih.gov/genbank/gbrel.txt) section 3.4.4 for more info.)

> However, the 10 characters in the locus name are no longer sufficient to represent the amount of information originally intended to be contained in the locus name. The only rule now applied in assigning a locus name is that it must be unique. For example, for GenBank records that have 6-character accessions (e.g., U12345), the locus name is usually the first letter of the genus and species names, followed by the accession number. For 8-character character accessions (e.g., AF123456), the locus name is just the accession number.

Picking up this ticket now to implement the split-on-whitespace suggestion above!

**Comment by tcjaffe** [comment]
Hm, looks like mol type is sometimes absent which complicates things. Some tests currently break with just a whitespace split approach. Continuing to dig and read up on the GenBank format.

**Comment by padix-key** [comment]
Thanks for taking the issue. Apart from the ID field, the later fields seem to suffice some pattern. Hence, regex pattern matching might help here.
