### ISSUE TITLE
How to write custom annotation into pdb file?

### ISSUE THREAD

**Issue by diyang1354** [biotite-dev/biotite#497]
I've tried method in issue #487 but failed. 
For example, I add a custom annotation like this:

atom_array.add_annotation('exposure', dtype=str)
atom_array.exposure = ['e', 'e', 'e', 'b', 'b', 'b']
strucio.save_structure('test.pdb',atom_array)

However, the custom annotation category 'exposure' is not saved to .pdb, and error occurs when I run: 
mab_array = strucio.load_structure('test.pdb', extra_fields=['exposure'])

How can I solve this? Thanks

**Comment by padix-key** [comment]
The PDB format (as well as the other structure file formats supported by Biotite) does not allow for custom fields. Therefore, the `exposure` annotation is ignored. To solve you can usually use repurpose another supported field such as `b_factor` to store your data. This is for example the approach [Alphafold uses for storing the pLDDT](https://alphafold.ebi.ac.uk/faq). I your case you have letters a custom annotation, sothe `ins_code` annotation might work for you.
