### ISSUE TITLE
Support 5 characters in residue names

### ISSUE THREAD

**Issue by padix-key** [biotite-dev/biotite#500]
As mentioned in #498 the [PDB will introduce 5-letter residue names](https://www.rcsb.org/news/65007774d78e004e766a969d). To reflect this change multiple adaptions are necessary.

- Read `res_name` as `U5` arrays also from other sources.
- Raise an exception when writing formats that do not support 5-letter residue names, if the structure contains such residue names.
- Adapt tests and doctests.
- Mention this new data type in structure documentation.

**Comment by xvlaurent** [comment]
Hello @padix-key!

Do you think it would be possible to have a release with those enhancement before the switch to 5 residue codes happen in december?

Would be happy to help, but I'm not sure to be able to identify all the impacted code sections.

**Comment by padix-key** [comment]
I plan to begin tackling this issue end of this week. This change will come into effect at the beginning of 2024, right? I am not completely sure I will manage to create a new release until then, but I am quite confident.

**Comment by xvlaurent** [comment]
Great, thanks!
Last info I found, new entries with 5 character residue codes are still predicted to arrive end of December.

**Comment by padix-key** [comment]
I prepared a fix. It was easier than expected, because I forgot that most `structure.io.*` subpackages already use the dtype set in `atoms.py`
