### ISSUE TITLE
Getting CIGAR string of an alignment

### ISSUE THREAD

**Issue by padix-key** [biotite-dev/biotite#507]
A function `biotite.sequence.align.get_cigar(alignment)` is requested that computes a CIGAR string from an `Alignment`. This allows better interaction with external alignment (file) formats, such as SAM.

**Comment by MaxGreil** [comment]
I would like to take over this issue.

**Comment by padix-key** [comment]
I am already working on this issue. Sorry, I should have assigned myself to it.
