### ISSUE TITLE
`mmtf` being officiallity deprecated & not served.

### ISSUE THREAD

**Issue by BradyAJohnston** [biotite-dev/biotite#525]
`bcif` is the replacement for `mmtf`, and some databases such as RCSB are going to stop serving `mmtf` later this year.

https://www.rcsb.org/news/feature/65a1af31c76ca3abcc925d0c

**Comment by padix-key** [comment]
Thanks for notifying me. Until now I hesitated to implement `bcif` support, as it was not clear to me, if `bcif` will be long-term supported by the PDB. This is now a clear signal.

**Comment by BradyAJohnston** [comment]
Thanks @padix-key for doing all this work! I've been watching the re-write of the CIF / BCIF and I'm liking the interface. Do you have a plan to make a new release soon? I would love to include the new `.bcif` support in Molecular Nodes as soon as it's released :)

**Comment by padix-key** [comment]
Hi, thank you. The next version will be probably released this month.
