### ISSUE TITLE
Feature request: protein structure alignment

### ISSUE THREAD

**Issue by pengtb** [biotite-dev/biotite#527]
biotite is great, though sth like [cealign](https://biopython.org/docs/dev/api/Bio.PDB.cealign.html) implemented in biopython is quite needed.

**Comment by pengtb** [comment]
there's a biotite.structure.superpose function

**Comment by padix-key** [comment]
Hi, I just wanted to note, that these two functions are not eqivialent `biotite.structure.superimpose()` uses the classic Kabsch algorithm. while `Bio.PDB.cealign` uses [this](https://pubmed.ncbi.nlm.nih.gov/9796821/) one.
