### ISSUE TITLE
pdbx.get_assembly` does not support multiple operation in one line?

### ISSUE THREAD

**Issue by 0ut0fcontrol** [biotite-dev/biotite#545]
Expected Behavior
1ben assembly 3 should have {A,B,C,D,E,F,G,H,I,J,K,L,M}, but only {A, B, C, D} in get_assembly() ouput.
| molstar show assembly 3 | biotite get_assembly(assembly_id="3")|
| ---| ---|
| ![image](https://github.com/biotite-dev/biotite/assets/11703338/ff5d83c6-398d-468a-abc8-77a97dddf13d)| ![image](https://github.com/biotite-dev/biotite/assets/11703338/dd9a039e-f021-4500-8667-78457f2ec26c)|

Example Script
```
from biotite.structure.io.pdbx import PDBxFile, get_assembly, list_assemblies
from biotite.database import rcsb
import biotite.structure.io as strucio

f = PDBxFile.read(rcsb.fetch("1ben", "cif"))
f.write("1ben.cif")

# cif block in 1ben
""" 
loop_
_pdbx_struct_assembly_gen.assembly_id 
_pdbx_struct_assembly_gen.oper_expression 
_pdbx_struct_assembly_gen.asym_id_list 
1  1     A,B,E,J,K                 
2  1     C,D,F,G,H,I,L,M           
3  1,2,3 A,B,C,D,E,F,G,H,I,J,K,L,M 
4  1,2,3 C,D,F,G,H,I,L,M           
4  4,5,6 A,B,E,J,K         
"""

print(f.get_category("pdbx_struct_assembly_gen")["asym_id_list"][2])
# output: A,B,C,D,E,F,G,H,I,J,K,L,M

assembly_atoms = get_assembly(f, assembly_id="3")
strucio.save_structure("1ben_3.cif", assembly_atoms)
print(set(assembly_atoms.chain_id))
# output: {'D', 'C', 'B', 'A'}
# missing E,F,G,H,I,J,K,L,M
```

**Comment by 0ut0fcontrol** [comment]
using ` use_author_fields=False` make the chain_ids match with asym_id_list.
```
from biotite.structure.io.pdbx import PDBxFile, get_assembly, list_assemblies
from biotite.database import rcsb
import biotite.structure.io as strucio

f = PDBxFile.read(rcsb.fetch("1ben", "cif"))
f.write("1ben.cif")

# cif block in 1ben
""" 
loop_
_pdbx_struct_assembly_gen.assembly_id 
_pdbx_struct_assembly_gen.oper_expression 
_pdbx_struct_assembly_gen.asym_id_list 
1  1     A,B,E,J,K                 
2  1     C,D,F,G,H,I,L,M           
3  1,2,3 A,B,C,D,E,F,G,H,I,J,K,L,M 
4  1,2,3 C,D,F,G,H,I,L,M           
4  4,5,6 A,B,E,J,K         
"""

print(f.get_category("pdbx_struct_assembly_gen")["asym_id_list"][2])
# output: A,B,C,D,E,F,G,H,I,J,K,L,M

assembly_atoms = get_assembly(f, assembly_id="3", use_author_fields=False)
strucio.save_structure("1ben_3_biotite.pdb", assembly_atoms)
strucio.save_structure("1ben_3_biotite.cif", assembly_atoms)
print(set(assembly_atoms.chain_id))
# output
# {'A', 'J', 'C', 'K', 'M', 'G', 'E', 'F', 'D', 'L', 'B', 'H', 'I'} 
```

But visulization still has problem:
| biotite output file | molstar | pymol | UCSF Chimera |
| --- | --- | --- | --- |
| 1ben_3.cif | ![](https://github.com/biotite-dev/biotite/assets/11703338/98521c12-1b35-47a8-9275-e9dc23fbd222)| ![](https://github.com/biotite-dev/biotite/assets/11703338/c65376d2-b098-4ae7-9622-4bfe96631c09) | ![](https://github.com/biotite-dev/biotite/assets/11703338/59ab895c-6435-4893-8f3c-29f229520c84) |
| 1ben_3.pdb | ![](https://github.com/biotite-dev/biotite/assets/11703338/16002fc5-d2da-49e6-a736-1ba9d3ae6c6d)| ![](https://github.com/biotite-dev/biotite/assets/11703338/533e8b0d-a998-4724-94bc-f3420802f6ab) | ![](https://github.com/biotite-dev/biotite/assets/11703338/97aa0cd7-662b-4e88-a419-9aaad0824772) |

[1ben_3_biotite.pdb.txt](https://github.com/biotite-dev/biotite/files/14823791/1ben_3_biotite.pdb.txt)
[1ben_3_biotite.cif.txt](https://github.com/biotite-dev/biotite/files/14823792/1ben_3_biotite.cif.txt)

**Comment by padix-key** [comment]
Hi, thanks for the detailed report. I looked into the structure: Actually, all chains from the assembly are present in the `AtomArray`/`AtomArrayStack`. However, the visualization programs do not correctly recognize the additional chains with the same chain ID, so the chains are not rendered or, in the case of Chimera, rendered with weird bonds. As you see in the Chimera PDB case all atoms are present.

A way to solve this is to relabel the chains, so that each chain is unique. As an example I modified your snippet:

```python
from biotite.structure.io.pdbx import PDBxFile, get_assembly
from biotite.database import rcsb
import biotite.structure.io as strucio
import biotite.structure as struc
import string

f = PDBxFile.read(rcsb.fetch("1ben", "cif"))
assembly_atoms = get_assembly(f, assembly_id="3", use_author_fields=False)

assembly_atoms = assembly_atoms[..., struc.filter_amino_acids(assembly_atoms)]
chain_starts = struc.get_chain_starts(assembly_atoms, add_exclusive_stop=True)
for i in range(len(chain_starts) - 1):
    assembly_atoms.chain_id[chain_starts[i] : chain_starts[i+1]] = string.ascii_uppercase[i]

strucio.save_structure("1ben_3_biotite.pdb", assembly_atoms)
strucio.save_structure("1ben_3_biotite.cif", assembly_atoms)
```

When you render it (at least with PyMol) all chains are present.

Feel free to reopen the issue, if your problem persists.
