### ISSUE TITLE
DeserializationError: Failed to deserialize category 'pdbx_struct_assembly_gen'

### ISSUE THREAD

**Issue by 0ut0fcontrol** [biotite-dev/biotite#554]
parsing pdb nextgen archive raise DeserializationError.

example: 8h2u
<img width="1706" alt="image" src="https://github.com/biotite-dev/biotite/assets/11703338/a87e7943-07c6-4c70-bdc6-bafbf6d632a1">

rcsb cif: https://files.rcsb.org/download/8h2u.cif
nextgen cif：https://files-nextgen.wwpdb.org/pdb_nextgen/data/entries/divided/h2/pdb_00008h2u/pdb_00008h2u_xyz-enrich.cif.gz

**Comment by 0ut0fcontrol** [comment]
modify `_to_single()` solve the problem:

<img width="775" alt="image" src="https://github.com/biotite-dev/biotite/assets/11703338/b456ae96-e64a-431d-91a3-25ffdbcd7318">

**Comment by padix-key** [comment]
Thanks for the precise pinpointing. I think this modification should work. You should even be able to replace the condition above (981 - 984) with it. As you already have the fix, would you also like to create the pull request?
