### ISSUE TITLE
little bug of `biotite.structure.dot_bracket_from_structure`

### ISSUE THREAD

**Issue by flyfyyfyy** [biotite-dev/biotite#556]
When the input of `biotite.structure.dot_bracket_from_structure` doesn't have any base pairs, `biotite.structure.base_pairs` will return an empty NumPy array `array([], dtype=float64)`. 
When `np.sort(basepairs, axis=1)` is applied to this empty array, it will raise an` AxisError: axis 1 is out of bounds for array of dimension 1`, causing the `dot_bracket_from_structure` function to fail.

Of course, that was just a minor issue. Your package is really powerful.

**Comment by t0mdavid-m** [comment]
Hi,
thanks a lot for the bug report! I will look into it over the next couple days.
