### ISSUE TITLE
strucio.save_structure rips up structure from MD containing ligand

### ISSUE THREAD

**Issue by entropybit** [biotite-dev/biotite#562]
Hi, 

I have had it in the past too, that when I use ``strucio.save_structure`` to save the frame from a loaded
MD trajectory, e.g. an XTC or in this case DCD file, that the resulting structure was messed up wehn loading it in pymol.
Even after running DSS. That was sometimes still acceptable as I could visualize the surface but still unsatisfactory which is why I usually
do that now by using gmx trjconv. However in OpenMM there is no such tool therefore you have to do it yourself.

Anyways coming to the issue I observed: When I write frames from my trajectory in to a multi model PDB file like this

```python
frames=np.arange(0, trajectories_espaloma[0].shape[0], trajectories_espaloma[0].shape[0]/100)
for i, trajectory_espaloma in enumerate(trajectories_espaloma):
    name = "ligand_mistake_reproduce/traj_rough_aligned_" + str(logs_T_traj[i]) + ".pdb"
    strucio.save_structure(name, trajectory_espaloma[frames.astype(int)])
```

The resulting structure in pymol does not look right. As mentioned the protein structure can not be retrieved even after running dss, whats more however, is the fact that the atoms in my ligand appear to have changed. Some of the carbon atoms became oxygen, which shows me a ligand with oxygen inside the ring having a triple bond. 

For comparison sakes I did the same thing with mdtrajs tool mdconvert and there this does not hapen.
I will add a visualizations of the two generated structures and highlight the wrong oxygens in the following:

The frames I get using save_structure:
![biotite](https://github.com/biotite-dev/biotite/assets/10496600/d2dda84c-4aba-4cef-900b-c68fb0b1e46a)

The same frames I get using mdconvert:
![mdconvert](https://github.com/biotite-dev/biotite/assets/10496600/10d08c7e-371c-4c55-ad23-8224cfa30439)

I can also share some data and an complete script if necessary.

Update: Also tried to use PDBFile directly yielding the same results.

**Comment by entropybit** [comment]
Okay, turns out that OpenMM changes the order of the atoms from the input. Therefore the coordinates are correct but the labeling is just wrong. Reloading the trajectory with a pdb that contains the minimized system as output from OpenMM worked just fine. One simple thing too note is that the Ligand was labeled as UNK and this lead to it being recongized as a amino acid. 
Which is why it was still in the structure although I did do this

```python
protein_mask = struc.filter_amino_acids(template) 
template = template[protein_mask]
```

I am closing this issue again but would propose implementing checks.
Also for the mismatch in ordering between input and trajectory a complicated test can be written that might be used uppon specification.

**Comment by padix-key** [comment]
If you want to use OpenMM together with Biotite, you might also consider using https://github.com/biotite-dev/molmarbles.

Regarding the missing amino acid connections in PyMOL, I am not sure what the problems causes.
You might try adding bonds to the `AtomArray` via `connect_via_residue_names()` or writing a CIF file instead of PDB.
