### ISSUE TITLE
Full support of SDFiles

### ISSUE THREAD

**Issue by padix-key** [biotite-dev/biotite#566]
Currently `MolFile` already has also rudimentary support for files in SDF format. However, there is no support for

- multi-entry SDF files
- metadata in SDF files

A new `SDFile` class should be able to solve this issue.

**Comment by entropybit** [comment]
My pull request https://github.com/biotite-dev/biotite/pull/418
should do just that when its done or am I missing something ?
I will start working on that soon as I also need those functionalities.
My apologies for taking so long.

**Comment by padix-key** [comment]
You are right, I forgot this PR exists. Since I also need support for multi-entry SDF files, I would `git cherry-pick` the your related commits from the PR and finalize the feature. Then you can still continue working on `xyz` and `mol2` format.

**Comment by entropybit** [comment]
Okay, pleas do so. Essentially only the reading the meta information into a dictionary funcitonality was missing if I remember correctly.

**Comment by padix-key** [comment]
Fixed by #589.
