### ISSUE TITLE
biotite 0.41.1 `.whl` not available for MacOS ARM

### ISSUE THREAD

**Issue by BradyAJohnston** [biotite-dev/biotite#605]
I'm not sure on the particulars of the build pipeline - but after you tweaked the build parameters, `0.41.1` isn't available as a `.wh` for my macOS ARM machine. From looking at the versions - the ARM build is now on `macosx_10_16` where previously it was `macosx_11_0`. 

It's a niche because I'm using the pre-built `.whl` builds to package up for a Blender extension - but I'm wondering if this might be expanded to include a later `macosx` version?

**Comment by padix-key** [comment]
I do not know exactly why changing the build backend changed also the wheel version, but after updating the OS version in the CI as well, the distribution is `macosx_11_0_arm64` again. We will create a patch version for it.

**Comment by BradyAJohnston** [comment]
thanks mate!

**Comment by padix-key** [comment]
With `0.41.2`released the correct wheel should be present. Can you confirm?

**Comment by BradyAJohnston** [comment]
Yep I can download without issue now - thanks!
