### ISSUE TITLE
Biotite dssp not running! Subprocess error: code 6

### ISSUE THREAD

**Issue by padix-key** [biotite-dev/biotite#607]
### Discussed in https://github.com/biotite-dev/biotite/discussions/606

<div type='discussions-op-text'>

<sup>Originally posted by **intomybioverse** June 22, 2024</sup>
Hello everyone.

I am trying to run the biotite secondary structure analysis program in wsl to study the secondary structure of a protein after md simulation. The website link for the python code is provided below.

[Secondary structure of protein during an MD simulation using Biotite] ([Secondary structure during an MD simulation — Biotite 0.41.0 documentation ](https://www.biotite-python.org/examples/gallery/structure/trajectory_sse.html))

However, I am getting the following error:
Traceback (most recent call last):
File “/home/sobs/AvrPto/6M/trajectory_sse.py”, line 43, in
app.join()
File “/home/sobs/.local/biotite_env/lib/python3.10/site-packages/biotite/application/application.py”, line 63, in wrapper
return func(*args, **kwargs)
File “/home/sobs/.local/biotite_env/lib/python3.10/site-packages/biotite/application/localapp.py”, line 257, in join
self.evaluate()
File “/home/sobs/.local/biotite_env/lib/python3.10/site-packages/biotite/application/dssp/app.py”, line 90, in evaluate
super().evaluate()
File “/home/sobs/.local/biotite_env/lib/python3.10/site-packages/biotite/application/localapp.py”, line 278, in evaluate
raise SubprocessError(
subprocess.SubprocessError: ‘mkdssp’ returned with exit code -6: mkdssp: ./src/CifParser.cpp:330: cif::SacParser::CIFToken cif::SacParser::getNextToken(): Assertion `mTokenValue.length() >= 3’ failed.

I am using python3.10 for this program, biotite has been installed, it has a sub-package dssp. Additionally, I have installed dssp as well. Yet, I am getting this error. Can you please help out?

</div>

**Comment by padix-key** [comment]
Thanks for the report. However it is hard to pinpoint the cause remotely. Hence here a few questions:

- Which Biotite version are you using? There is a potentially important CIF file fix in Biotite 0.41: #586
- Does it work for you with the original data from https://www.biotite-python.org/examples/gallery/structure/trajectory_sse.html?
- Could you check if it also fails when you input the template `AtomArray` directly to `DsspApp`, i.e. the one loaded from `templ_file_path`.
- If it does not fail for the template, does it fail already for the first frame of the trajectory?

**Comment by intomybioverse** [comment]
1. Yes, I am using Biotite 0.41. 
Name: biotite
Version: 0.41.1
Summary: A comprehensive library for computational molecular biology
Home-page:
Author: The Biotite contributors...

**How to fix the CIF file issue?**

2. No even with lysozyme_md.pdb and lysozyme_md.xtc I am getting the same error. 

3. "Could you check if it also fails when you input the template AtomArray directly to DsspApp, i.e. the one loaded from templ_file_path." 
**Can you please explain what I should do regarding this?**

4. Yes, it fails for the only first frame too.

**Comment by padix-key** [comment]
OK, you data seems not to be the problem then.

> Can you please explain what I should do regarding this?

In this case we can skip this. The other possible culprits are WSL and the DSSP version. I just recognized that there are newer DSSP versions not on Conda yet. If installed from `environment.yml` DSSP `2.2.1` is installed, which seems to work fine.

Could you check your DSSP version? If it deviates from `2.2.1` could you install `2.2.1` (e.g. via Conda) and check if it works?

**Comment by intomybioverse** [comment]
I tried getting dssp-2.2.1 through environment.yml using conda, but I am getting this error.

(myenv) sobs@BEE:~/miniconda3/envs$ conda env create -f environment.yml
Channels:
 - conda-forge
 - defaults
 - bioconda
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - dssp==2.2.1

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://conda.anaconda.org/bioconda/linux-64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

I have downloaded the dssp=2.2.1 package from https://src.fedoraproject.org/repo/pkgs/dssp/dssp-2.2.1.tgz/  but while installing it i got this error message. 

(myenv) sobs@BEE:~/.local/biotite_env/dssp-2.2.1$ make
compiling obj/mkdssp.o
In file included from src/structure.h:8,
                 from src/mkdssp.cpp:27:
src/primitives-3d.h:12:10: fatal error: boost/tr1/tuple.hpp: No such file or directory
   12 | #include <boost/tr1/tuple.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [makefile:64: obj/mkdssp.o] Error 1

How should I proceed now?

**Comment by padix-key** [comment]
You can install it with Conda from the `salilab` channel (https://anaconda.org/salilab/dssp):

```
conda install -c salilab "dssp=2.2.1"
```

**Comment by intomybioverse** [comment]
Yes, it is working now. Thanks.

**Comment by padix-key** [comment]
Great! Still the `DsspApp` interface should be made compatible with newer DSSP versions as well. Hence, I will create a follow-up issue.

**Comment by padix-key** [comment]
Do you know which DSSP version you used before?
