### ISSUE TITLE
Bug: Deserialization of some CIF blocks

### ISSUE THREAD

**Issue by Croydon-Brixton** [biotite-dev/biotite#648]
The `v1.0.0` release has a pretty serious bug for deserializing some CIF files.

**Description**:
When deserializing CIF files for some pdbs (e.g. [`5gam`](https://[files.rcsb.org/view/5GAM.cif](https://files.rcsb.org/view/5GAM.cif))) the deserialization fails to parse the lines correctly.

You can reproduce it e.g. for the `entity` field with 
```python
import biotite.structure.io.pdbx as pdbx
from tempfile import gettempdir
import biotite.database.rcsb as rcsb

cif_file_path = rcsb.fetch("5gam", "cif", gettempdir())
cif_file = pdbx.CIFFile.read(cif_file_path)
cif_file.block["entity"]
category = cif_file.block["entity"]
column = category["id"]
data = column.data
print(data.array)

# Output
# ['1' '2' '3' '4' 'The 5'
# 'Small nuclear ribonucleoprotein-associated protein B'
#  'Small nuclear ribonucleoprotein E' 'Small nuclear ribonucleoprotein F'
# 'Small nuclear ribonucleoprotein G' 'Unknown polypeptide'
# 'Small nuclear ribonucleoprotein Sm D3'
# 'Small nuclear ribonucleoprotein Sm D1'
# 'Small nuclear ribonucleoprotein Sm D2' "GUANOSINE-5'-TRIPHOSPHATE"]
```

**Solution**:
I have traced the problem down to [commit `0404084`](https://github.com/biotite-dev/biotite/commit/0404084283765baef765cc869d86ee07a898d82f). When reverting this specific commit, the file is parsed correctly again. Biotite versions prior to `1.0.0` do not have this commit and work fine.

**Comment by padix-key** [comment]
Thank you for the report and the thorough investigation. This commit resolves #570, so simply reverting it breaks the CIF format in other cases. But I already have solution in mind, I will create a PR tomorrow.
