### ISSUE TITLE
 ImportError: cannot import name 'filter_backbone' from 'biotite.structure'

### ISSUE THREAD

**Issue by marjanUofT** [biotite-dev/biotite#656]
I am getting above issue for my code since today morning. I couldn't find any changes and update to fix this issue.

**Comment by padix-key** [comment]
The function was superseded by [`filter_peptide_backbone()`](https://www.biotite-python.org/latest/apidoc/biotite.structure.filter_peptide_backbone.html). `filter_backbone()` was previously deprecated and removed in version `1.0`
