### ISSUE TITLE
Vectorize apply_residue_wise

### ISSUE THREAD

**Issue by alex-hh** [biotite-dev/biotite#675]
Hi,

Thanks for this great library! Im interested in optimising the efficiency of all my data processing pipelines at the moment and wonder whether it would make sense to vectorise apply_residue_wise, by replacing the apply_segment_wise invocation with some np.vectorise statement?

**Comment by padix-key** [comment]
Hi, I do not think that `np.vectorize` will give a significant performance boost, as the underlying code is still pure Python. To cite from the [NumPy docs](https://numpy.org/doc/stable/reference/generated/numpy.vectorize.html):

> The `vectorize` function is provided primarily for convenience, not for performance. The implementation is essentially a for loop.

**Comment by alex-hh** [comment]
Ah I see, thanks for pointing that out
