### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by FL-ECHE** [biotite-dev/biotite#706]
After installing either 1.0.1 or 0.41.2, I cannot access any method, here is the result of dir(biotite) :
```
['AdaptiveFancyArrow', 'Copyable', 'DeserializationError', 'File', 'InvalidFileError', 'SerializationError', 'TextFile', '__author__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '__version_tuple__', 'colors', 'copyable', 'file', 'set_font_size_in_coord', 'temp', 'temp_dir', 'temp_file', 'version', 'visualize']
```

I used `pip install biotite` on Mac ARM (M3 Pro)

**Comment by padix-key** [comment]
Hi. The output seems fine to me. Can you specify what exactly is not working? Most of the user-faced functionalities is in subpackages of Biotite e.g. `biotite.structure`.

**Comment by FL-ECHE** [comment]
Hi, sorry if I explained badly, I get 'AttributeError: module 'biotite' has no attribute 'sequence'', I cannot seem to access any of biotite sub packages

**Comment by padix-key** [comment]
Have you tried
```
import biotite.sequence as seq
```
or
```
from biotite.sequence import ProteinSequence
```
?

Is this the first Biotite installation in an environment or did you update Biotite?

**Comment by FL-ECHE** [comment]
Ok both of these seem to work for me, I apologize for the waste of time, I only tried accessing through biotite.sequence.ProteinSequence and it threw the error, I don't exactly get why it works this way but it's probably an oversight on my end. Thank you for your help.
