### ISSUE TITLE
b factor (pLDDT) from cif files 

### ISSUE THREAD

**Issue by carolinelennartsson** [biotite-dev/biotite#717]
Hej, 

Thanks for a great package. 

I'd like some help with extracting the b factor from a cif file. I can't figure of from the documeentation if there is functionallity for this? 

cif_file = pdbx.CIFFile.read(f) 
array = pdbx.get_structure(cif_file, model = 1)
then get b factors for all atoms 

My structure is an AlphaFold structure so it's actually the pLDDT im trying to extract, but should be stored under b factor in the file? 

Thank you for your help, Caroline :)

**Comment by BradyAJohnston** [comment]
You can use the 'extra_fields' to access them get getting the structure.

```py
cif_file = CIFFile.read(f)
array = pdbx.get_structure(f, extra_fields = ["b_factor"])
array.b_factor
```
```
array([43.88, 55.8 , 57.97, ..., 58.61, 68.15, 57.4 ])
```

**Comment by padix-key** [comment]
For the sake of completeness, you can also extract the pLDDT from the `ma_qa_metric_local` category:
```python
pdbx_file = pdbx.CIFFile.read(cif_path)
plddt = pdbx_file.block["ma_qa_metric_local"]["metric_value"].as_array(
    dtype=np.float32
)
```
